# Generated by Django 3.2.6 on 2022-01-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220109_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
